### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by sefinek** [MainSilent/linux.js#3]
how to fix this issue?

video: https://sefinek.net/images/screenshots/23.10.2022/VirtualBoxVM_hhP7ECzfV4h7.mp4

**Comment by sefinek** [comment]
index.js
```js
const { app, BrowserWindow } = require('electron');

function createWindow() {
    const mainWindow = new BrowserWindow({
        width: 800,
        height: 600
    });
    mainWindow.loadFile('./index.html');
}

app.on('ready', createWindow);
```

**Comment by MainSilent** [comment]
Have you loaded the index.html file?

**Comment by sefinek** [comment]
> Have you loaded the index.html file?

yes, my package.json:

```json
{
  "name": "sraczuniaos",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "AppImage": "dist/sraczuniaos-1.0.0.AppImage",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron": "^21.2.0",
    "electron-builder": "^23.6.0"
  },
  "build": {
    "files": [
      "index.js",
      "index.html"
    ],
    "linux": {
      "target": "AppImage"
    }
  },
  "dependencies": {
    "@mainsilent/linux.js": "^1.1.2"
  }
}
```

**Comment by MainSilent** [comment]
Would it work as you expected if you directly run `sraczuniaos-1.0.0.AppImage`?

**Comment by sefinek** [comment]
> Would it work as you expected if you directly run `sraczuniaos-1.0.0.AppImage`?

yup

![vmplayer_lePYqUcc8tXR](https://user-images.githubusercontent.com/92880265/197401598-222512c6-6c5e-4965-b77b-17f0fd39ce79.png)

**Comment by MainSilent** [comment]
I'm not sure about the cause, Can you try with the exact code(index.js and index.html) and package.json that is on the video?

**Comment by sefinek** [comment]
```js
const { app, BrowserWindow } = require('electron');

function createWindow() {
    const mainWindow = new BrowserWindow({
         fullscreen: true
    });
    mainWindow.loadFile('index.html');
}

app.whenReady().then(() => {
    createWindow()
});
```

**Comment by sefinek** [comment]
vid: https://sefinek.net/idk.mp4

**Comment by MainSilent** [comment]
Can you try with electron `^13.2.2` and electron-builder `^22.11.7`?

**Comment by sefinek** [comment]
thx https://sefinek.net/images/screenshots/23.10.2022/vmplayer_cQvsLS6JFe2Q.png
